export const STATES = [
  { stateCode: 'AL', stateName: 'Alabama' },
  { stateCode: 'AK', stateName: 'Alaska' },
  { stateCode: 'AS', stateName: 'American Samoa' },
  { stateCode: 'AZ', stateName: 'Arizona' },
  { stateCode: 'AR', stateName: 'Arkansas' },
  { stateCode: 'CA', stateName: 'California' },
  { stateCode: 'CO', stateName: 'Colorado' },
  { stateCode: 'CT', stateName: 'Connecticut' },
  { stateCode: 'DE', stateName: 'Delaware' },
  { stateCode: 'DC', stateName: 'District Of Columbia' },
  { stateCode: 'FL', stateName: 'Florida' },
  { stateCode: 'GA', stateName: 'Georgia' },
  { stateCode: 'HI', stateName: 'Hawaii' },
  { stateCode: 'ID', stateName: 'Idaho' },
  { stateCode: 'IL', stateName: 'Illinois' },
  { stateCode: 'IN', stateName: 'Indiana' },
  { stateCode: 'IA', stateName: 'Iowa' },
  { stateCode: 'KS', stateName: 'Kansas' },
  { stateCode: 'KY', stateName: 'Kentucky' },
  { stateCode: 'LA', stateName: 'Louisiana' },
  { stateCode: 'ME', stateName: 'Maine' },
  { stateCode: 'MH', stateName: 'Marshall Islands' },
  { stateCode: 'MD', stateName: 'Maryland' },
  { stateCode: 'MA', stateName: 'Massachusetts' },
  { stateCode: 'MI', stateName: 'Michigan' },
  { stateCode: 'FM', stateName: 'Micronesia' },
  { stateCode: 'MN', stateName: 'Minnesota' },
  { stateCode: 'MS', stateName: 'Mississippi' },
  { stateCode: 'MO', stateName: 'Missouri' },
  { stateCode: 'MT', stateName: 'Montana' },
  { stateCode: 'NE', stateName: 'Nebraska' },
  { stateCode: 'NV', stateName: 'Nevada' },
  { stateCode: 'NH', stateName: 'New Hampshire' },
  { stateCode: 'NJ', stateName: 'New Jersey' },
  { stateCode: 'NM', stateName: 'New Mexico' },
  { stateCode: 'NY', stateName: 'New York' },
  { stateCode: 'NC', stateName: 'North Carolina' },
  { stateCode: 'ND', stateName: 'North Dakota' },
  { stateCode: 'MP', stateName: 'Northern Marianas' },
  { stateCode: 'OH', stateName: 'Ohio' },
  { stateCode: 'OK', stateName: 'Oklahoma' },
  { stateCode: 'OR', stateName: 'Oregon' },
  { stateCode: 'PW', stateName: 'Palau' },
  { stateCode: 'PA', stateName: 'Pennsylvania' },
  { stateCode: 'PR', stateName: 'Puerto Rico' },
  { stateCode: 'RI', stateName: 'Rhode Island' },
  { stateCode: 'SC', stateName: 'South Carolina' },
  { stateCode: 'SD', stateName: 'South Dakota' },
  { stateCode: 'TN', stateName: 'Tennessee' },
  { stateCode: 'TX', stateName: 'Texas' },
  { stateCode: 'UT', stateName: 'Utah' },
  { stateCode: 'VT', stateName: 'Vermont' },
  { stateCode: 'VI', stateName: 'Virgin Islands' },
  { stateCode: 'VA', stateName: 'Virginia' },
  { stateCode: 'WA', stateName: 'Washington' },
  { stateCode: 'WV', stateName: 'West Virginia' },
  { stateCode: 'WI', stateName: 'Wisconsin' },
  { stateCode: 'WY', stateName: 'Wyoming' },
];

export const COUNTRIES = [
  { countryCode: 'us', countryName: '🇺🇸 United States' },
  { countryCode: 'af', countryName: '🇦🇫 Afghanistan' },
  { countryCode: 'ax', countryName: 'Aland Islands' },
  { countryCode: 'al', countryName: '🇦🇱 Albania' },
  { countryCode: 'dz', countryName: '🇩🇿 Algeria' },
  { countryCode: 'as', countryName: '🇦🇸 American Samoa' },
  { countryCode: 'ad', countryName: '🇦🇩 Andorra' },
  { countryCode: 'ao', countryName: '🇦🇴 Angola' },
  { countryCode: 'ai', countryName: '🇦🇮 Anguilla' },
  { countryCode: 'ag', countryName: '🇦🇬 Antigua and Barbuda' },
  { countryCode: 'ar', countryName: '🇦🇷 Argentina' },
  { countryCode: 'am', countryName: '🇦🇲 Armenia' },
  { countryCode: 'aw', countryName: '🇦🇼 Aruba' },
  { countryCode: 'au', countryName: '🇦🇺 Australia' },
  { countryCode: 'at', countryName: '🇦🇹 Austria' },
  { countryCode: 'az', countryName: '🇦🇿 Azerbaijan' },
  { countryCode: 'bs', countryName: '🇧🇸 Bahamas' },
  { countryCode: 'bh', countryName: '🇧🇭 Bahrain' },
  { countryCode: 'bd', countryName: '🇧🇩 Bangladesh' },
  { countryCode: 'bb', countryName: '🇧🇧 Barbados' },
  { countryCode: 'by', countryName: '🇧🇾 Belarus' },
  { countryCode: 'be', countryName: '🇧🇪 Belgium' },
  { countryCode: 'bz', countryName: '🇧🇿 Belize' },
  { countryCode: 'bj', countryName: '🇧🇯 Benin' },
  { countryCode: 'bm', countryName: '🇧🇲 Bermuda' },
  { countryCode: 'bt', countryName: '🇧🇹 Bhutan' },
  { countryCode: 'bo', countryName: '🇧🇴 Bolivia' },
  { countryCode: 'ba', countryName: '🇧🇦 Bosnia and Herzegovina ' },
  { countryCode: 'bw', countryName: '🇧🇼 ️️Botswana' },
  { countryCode: 'bv', countryName: '🇳🇴 Bouvet Island' },
  { countryCode: 'br', countryName: '🇧🇷 Brazil' },
  { countryCode: 'vg', countryName: 'British Virgin Islands' },
  { countryCode: 'bn', countryName: '🇧🇳 Brunei' },
  { countryCode: 'bg', countryName: '🇧🇬 Bulgaria' },
  { countryCode: 'bf', countryName: '🇧🇫 Burkina Faso' },
  { countryCode: 'bi', countryName: '🇧🇮 Burundi' },
  { countryCode: 'kh', countryName: '🇰🇭 Cambodia' },
  { countryCode: 'cm', countryName: '🇨🇲 Cameroon' },
  { countryCode: 'ca', countryName: '🇨🇦 Canada' },
  { countryCode: 'cv', countryName: '🇨🇻 Cape Verde' },
  { countryCode: 'ky', countryName: '🇰🇾 Cayman Islands' },
  { countryCode: 'cf', countryName: '🇨🇫 Central African Republic' },
  { countryCode: 'td', countryName: 'Chad' },
  { countryCode: 'cl', countryName: '🇨🇱 Chile' },
  { countryCode: 'cn', countryName: '🇨🇳 China' },
  { countryCode: 'cx', countryName: 'Christmas Island' },
  { countryCode: 'cc', countryName: 'Cocos Islands' },
  { countryCode: 'co', countryName: '🇨🇴 Colombia' },
  { countryCode: 'km', countryName: '🇰🇲 Comoros' },
  { countryCode: 'cd', countryName: '🇨🇩 Congo' },
  { countryCode: 'cg', countryName: '🇨🇬 Congo Brazzaville' },
  { countryCode: 'ck', countryName: '🇨🇰 Cook Islands' },
  { countryCode: 'cr', countryName: '🇨🇷 Costa Rica' },
  { countryCode: 'ci', countryName: '🇨🇮 Côte D’Ivoire' },
  { countryCode: 'hr', countryName: '🇭🇷 Croatia' },
  { countryCode: 'cu', countryName: '🇨🇺 Cuba' },
  { countryCode: 'cw', countryName: '🇨🇼 Curaçao' },
  { countryCode: 'cy', countryName: '🇨🇾 Cyprus' },
  { countryCode: 'cz', countryName: '🇨🇿 Czech Republic' },
  { countryCode: 'dk', countryName: '🇩🇰 Denmark' },
  { countryCode: 'dj', countryName: '🇩🇯 Djibouti' },
  { countryCode: 'dm', countryName: '🇩🇲 Dominica' },
  { countryCode: 'do', countryName: '🇩🇴 Dominican Republic' },
  { countryCode: 'ec', countryName: '🇪🇨 Ecuador' },
  { countryCode: 'eg', countryName: '🇪🇬 Egypt' },
  { countryCode: 'sv', countryName: '🇸🇻 El Salvador' },
  { countryCode: 'gb', countryName: '🇬🇧 England' },
  { countryCode: 'gq', countryName: '🇬🇶 Equatorial Guinea' },
  { countryCode: 'er', countryName: '🇪🇷 Eritrea' },
  { countryCode: 'ee', countryName: '🇪🇪 Estonia' },
  { countryCode: 'et', countryName: '🇪🇹 Ethiopia' },
  { countryCode: 'eu', countryName: 'European Union' },
  { countryCode: 'fk', countryName: 'Falkland Islands' },
  { countryCode: 'fo', countryName: '🇫🇴 Faroe Islands' },
  { countryCode: 'fj', countryName: '🇫🇯 Fiji' },
  { countryCode: 'fi', countryName: '🇫🇮 Finland' },
  { countryCode: 'fr', countryName: '🇫🇷 France' },
  { countryCode: 'gf', countryName: '🇬🇫 French Guiana' },
  { countryCode: 'pf', countryName: 'French Polynesia' },
  { countryCode: 'tf', countryName: '🇹🇫 French Southern Territories' },
  { countryCode: 'ga', countryName: '🇬🇦 Gabon' },
  { countryCode: 'gm', countryName: '🇬🇲 Gambia' },
  { countryCode: 'ge', countryName: '🇬🇪 Georgia' },
  { countryCode: 'de', countryName: '🇩🇪 Germany' },
  { countryCode: 'gh', countryName: '🇬🇭 Ghana' },
  { countryCode: 'gi', countryName: '🇬🇮 Gibraltar' },
  { countryCode: 'gr', countryName: '🇬🇷 Greece' },
  { countryCode: 'gl', countryName: 'Greenland' },
  { countryCode: 'gd', countryName: '🇬🇩 Grenada' },
  { countryCode: 'gp', countryName: '🇬🇵 Guadeloupe' },
  { countryCode: 'gu', countryName: '🇬🇺 Guam' },
  { countryCode: 'gt', countryName: '🇬🇹 Guatemala' },
  { countryCode: 'gn', countryName: '🇬🇳 Guinea' },
  { countryCode: 'gw', countryName: '🇬🇼 Guinea-Bissau' },
  { countryCode: 'gy', countryName: '🇬🇾 Guyana' },
  { countryCode: 'ht', countryName: '🇭🇹 Haiti' },
  { countryCode: 'hm', countryName: '🇦🇺 Heard and McDonald Islands' },
  { countryCode: 'hn', countryName: '🇭🇳 Honduras' },
  { countryCode: 'hk', countryName: '🇭🇰 Hong Kong' },
  { countryCode: 'hu', countryName: '🇭🇺 Hungary' },
  { countryCode: 'is', countryName: '🇮🇸 Iceland' },
  { countryCode: 'in', countryName: '🇮🇳 India' },
  { countryCode: 'io', countryName: 'Indian Ocean Territory' },
  { countryCode: 'id', countryName: '🇮🇩 Indonesia' },
  { countryCode: 'ir', countryName: '🇮🇷 Iran' },
  { countryCode: 'iq', countryName: '🇮🇶 Iraq' },
  { countryCode: 'ie', countryName: '🇮🇪 Ireland' },
  { countryCode: 'il', countryName: '🇮🇱 Israel' },
  { countryCode: 'it', countryName: '🇮🇹 Italy' },
  { countryCode: 'jm', countryName: '🇯🇲 Jamaica' },
  { countryCode: 'jp', countryName: '🇯🇵 Japan' },
  { countryCode: 'jo', countryName: '🇯🇴 Jordan' },
  { countryCode: 'kz', countryName: '🇰🇿 Kazakhstan' },
  { countryCode: 'ke', countryName: '🇰🇪 Kenya' },
  { countryCode: 'ki', countryName: '🇰🇮 Kiribati' },
  { countryCode: 'kw', countryName: '🇰🇼 Kuwait' },
  { countryCode: 'kg', countryName: '🇰🇬 Kyrgyzstan' },
  { countryCode: 'la', countryName: '🇱🇦 Laos' },
  { countryCode: 'lv', countryName: '🇱🇻 Latvia' },
  { countryCode: 'lb', countryName: '🇱🇧 Lebanon' },
  { countryCode: 'ls', countryName: '🇱🇸 Lesotho' },
  { countryCode: 'lr', countryName: '🇱🇷 Liberia' },
  { countryCode: 'ly', countryName: '🇱🇾 Libya' },
  { countryCode: 'li', countryName: '🇱🇮 Liechtenstein' },
  { countryCode: 'lt', countryName: '🇱🇹 Lithuania' },
  { countryCode: 'lu', countryName: '🇱🇺 Luxembourg' },
  { countryCode: 'mo', countryName: '🇲🇴 Macau' },
  { countryCode: 'mk', countryName: '🇲🇰 Macedonia' },
  { countryCode: 'mg', countryName: '🇲🇬 Madagascar' },
  { countryCode: 'mw', countryName: '🇲🇼 Malawi' },
  { countryCode: 'my', countryName: '🇲🇾 Malaysia' },
  { countryCode: 'mv', countryName: '🇲🇻 Maldives' },
  { countryCode: 'ml', countryName: '🇲🇱 Mali' },
  { countryCode: 'mt', countryName: '🇲🇹 Malta' },
  { countryCode: 'mh', countryName: 'Marshall Islands' },
  { countryCode: 'mq', countryName: '🇲🇶 Martinique' },
  { countryCode: 'mr', countryName: '🇲🇷 Mauritania' },
  { countryCode: 'mu', countryName: 'Mauritius' },
  { countryCode: 'yt', countryName: 'Mayotte' },
  { countryCode: 'mx', countryName: '🇲🇽 Mexico' },
  { countryCode: 'fm', countryName: 'Micronesia' },
  { countryCode: 'md', countryName: '🇲🇩 Moldova' },
  { countryCode: 'mc', countryName: 'Monaco' },
  { countryCode: 'mn', countryName: '🇲🇳 Mongolia' },
  { countryCode: 'me', countryName: '🇲🇪 Montenegro' },
  { countryCode: 'ms', countryName: '🇲🇸 Montserrat' },
  { countryCode: 'ma', countryName: '🇲🇦 Morocco' },
  { countryCode: 'mz', countryName: '🇲🇿 Mozambique' },
  { countryCode: 'mm', countryName: '🇲🇲 Myanmar' },
  { countryCode: 'na', countryName: '🇳🇦 Namibia' },
  { countryCode: 'nr', countryName: 'Nauru' },
  { countryCode: 'np', countryName: '🇳🇵 Nepal' },
  { countryCode: 'nl', countryName: '🇳🇱 Netherlands' },
  { countryCode: 'an', countryName: 'Netherlands Antilles' },
  { countryCode: 'nc', countryName: '🇳🇨 New Caledonia' },
  { countryCode: 'pg', countryName: '🇵🇬 Papua New Guinea' },
  { countryCode: 'nz', countryName: '🇳🇿 New Zealand' },
  { countryCode: 'ni', countryName: '🇳🇮 Nicaragua' },
  { countryCode: 'ne', countryName: '🇳🇪 Niger' },
  { countryCode: 'ng', countryName: '🇳🇬 Nigeria' },
  { countryCode: 'nu', countryName: '🇳🇺 Niue' },
  { countryCode: 'nf', countryName: 'Norfolk Island' },
  { countryCode: 'kp', countryName: '🇰🇵 North Korea' },
  { countryCode: 'mp', countryName: '🇲🇵 Northern Mariana Islands' },
  { countryCode: 'no', countryName: '🇳🇴 Norway' },
  { countryCode: 'om', countryName: '🇴🇲 Oman' },
  { countryCode: 'pk', countryName: '🇵🇰 Pakistan' },
  { countryCode: 'pw', countryName: '🇵🇼 Palau' },
  { countryCode: 'ps', countryName: '🇵🇸 Palestine' },
  { countryCode: 'pa', countryName: '🇵🇦 Panama' },
  { countryCode: 'py', countryName: '🇵🇾 Paraguay' },
  { countryCode: 'pe', countryName: '🇵🇪 Peru' },
  { countryCode: 'ph', countryName: '🇵🇭 Philippines' },
  { countryCode: 'pn', countryName: 'Pitcairn Islands' },
  { countryCode: 'pl', countryName: '🇵🇱 Poland' },
  { countryCode: 'pt', countryName: '🇵🇹 Portugal' },
  { countryCode: 'pr', countryName: '🇵🇷 Puerto Rico' },
  { countryCode: 'qa', countryName: '🇶🇦 Qatar' },
  { countryCode: 're', countryName: '🇷🇪 Réunion' },
  { countryCode: 'ro', countryName: '🇷🇴 Romania' },
  { countryCode: 'ru', countryName: '🇷🇺 Russia' },
  { countryCode: 'rw', countryName: '🇷🇼 Rwanda' },
  { countryCode: 'sh', countryName: 'Saint Helena' },
  { countryCode: 'kn', countryName: '🇰🇳 Saint Kitts and Nevis' },
  { countryCode: 'lc', countryName: '🇱🇨 Saint Lucia' },
  { countryCode: 'pm', countryName: 'Saint Pierre and Miquelon' },
  { countryCode: 'vc', countryName: '🇻🇨 Saint Vincent and Grenadines' },
  { countryCode: 'ws', countryName: '🇼🇸 Samoa' },
  { countryCode: 'sm', countryName: '🇸🇲 San Marino' },
  { countryCode: 'gs', countryName: 'Sandwich Islands' },
  { countryCode: 'st', countryName: '🇸🇹 São Tomé and Príncipe' },
  { countryCode: 'sa', countryName: '🇸🇦 Saudi Arabia' },
  { countryCode: 'sn', countryName: '🇸🇳 Senegal' },
  { countryCode: 'rs', countryName: '🇷🇸 Serbia' },
  { countryCode: 'sc', countryName: '🇸🇨 Seychelles' },
  { countryCode: 'sl', countryName: '🇸🇱 Sierra Leone' },
  { countryCode: 'sg', countryName: '🇸🇬 Singapore' },
  { countryCode: 'sx', countryName: '🇸🇽 Sint Maarten' },
  { countryCode: 'sk', countryName: '🇸🇰 Slovakia' },
  { countryCode: 'si', countryName: '🇸🇮 Slovenia' },
  { countryCode: 'sb', countryName: '🇸🇧 Solomon Islands' },
  { countryCode: 'so', countryName: '🇸🇴 Somalia' },
  { countryCode: 'za', countryName: '🇿🇦 South Africa' },
  { countryCode: 'ss', countryName: '🇸🇸 South Sudan' },
  { countryCode: 'kr', countryName: '🇰🇷 South Korea' },
  { countryCode: 'es', countryName: '🇪🇸 Spain' },
  { countryCode: 'lk', countryName: '🇱🇰 Sri Lanka' },
  { countryCode: 'sd', countryName: '🇸🇩 Sudan' },
  { countryCode: 'sr', countryName: '🇸🇷 Suriname' },
  { countryCode: 'sj', countryName: '🇳🇴 Svalbard' },
  { countryCode: 'sz', countryName: '🇸🇿 Swaziland' },
  { countryCode: 'se', countryName: '🇸🇪 Sweden' },
  { countryCode: 'ch', countryName: '🇨🇭 Switzerland' },
  { countryCode: 'sy', countryName: '🇸🇾 Syria' },
  { countryCode: 'tw', countryName: 'Taiwan' },
  { countryCode: 'tj', countryName: '🇹🇯 Tajikistan' },
  { countryCode: 'tz', countryName: '🇹🇿 Tanzania' },
  { countryCode: 'th', countryName: '🇹🇭 Thailand' },
  { countryCode: 'tl', countryName: '🇹🇱 Timor-Leste' },
  { countryCode: 'tg', countryName: '🇹🇬 Togo' },
  { countryCode: 'tk', countryName: '🇹🇷 Tokelau' },
  { countryCode: 'to', countryName: '🇹🇴 Tonga' },
  { countryCode: 'tt', countryName: '🇹🇹 Trinidad and Tobago' },
  { countryCode: 'tn', countryName: '🇹🇳 Tunisia' },
  { countryCode: 'tr', countryName: '🇹🇷 Turkey' },
  { countryCode: 'tm', countryName: '🇹🇲 Turkmenistan' },
  { countryCode: 'tc', countryName: '🇹🇨 Turks and Caicos Islands' },
  { countryCode: 'tv', countryName: '🇹🇻 Tuvalu' },
  { countryCode: 'ug', countryName: '🇺🇬 Uganda' },
  { countryCode: 'ua', countryName: '🇺🇦 Ukraine' },
  { countryCode: 'ae', countryName: '🇦🇪 United Arab Emirates' },
  { countryCode: 'gb', countryName: '🇬🇧 United Kingdom' },
  { countryCode: 'uy', countryName: '🇺🇾 Uruguay' },
  { countryCode: 'um', countryName: '🇺🇸 US Minor Islands' },
  { countryCode: 'vi', countryName: '🇻🇮 US Virgin Islands' },
  { countryCode: 'uz', countryName: '🇺🇿 Uzbekistan' },
  { countryCode: 'vu', countryName: '🇻🇺 Vanuatu' },
  { countryCode: 'va', countryName: 'Vatican City' },
  { countryCode: 've', countryName: '🇻🇪 Venezuela' },
  { countryCode: 'vn', countryName: '🇻🇳 Vietnam' },
  { countryCode: 'wf', countryName: 'Wallis and Futuna' },
  { countryCode: 'eh', countryName: 'Western Sahara' },
  { countryCode: 'ye', countryName: '🇾🇪 Yemen' },
  { countryCode: 'zm', countryName: '🇿🇲 Zambia' },
  { countryCode: 'zw', countryName: '🇿🇼 Zimbabwe' },
];
